* 
:properties:
:author: R S Milton, P Mirunalini, H Shahul Hamead
:date: 27 March 2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                              | L | T | P | E | C |
| UGE2176 | PROBLEM SOLVING AND PROGRAMMING IN PYTHON | 3 | 0 | 0 | 0 | 3 |
		
** R2021 CHANGES :noexport:
1. The knowledge level of unit1 was modified from K2 to K3
2. Unit1 was reordered
3. Reference book was added  for the unit1

** COURSE OBJECTIVES
- To learn algorithmic problem solving techniques.
- To learn the fundamentals of python programming.
- To compose programs in Python using conditions, iterations and decompose a problem into functions
- To construct programs in Python sequenced data type.
- To develop python programs using advanced constructs like dictionaries and files. 

{{{unit}}}
| UNIT I | ALGORITHMIC PROBLEM SOLVING  | 9 |
Logical and Algorithmic Thinking: Logical Thinking -- Algorithmic
Thinking; Problem Solving and Decomposition: Defining the Problem --
Devising the Solution -- Decomposition; Effective building blocks:
Basic Algorithmic Constructs (pseudo code, flow chart, programming
language) -- Program State.

{{{unit}}}
| UNIT II | DATA, EXPRESSION, STATEMENT, CONDITIONAL | 9 |
Data and types: int, float, boolean, string, list; variables,
expressions, statements, simultaneous assignment, precedence of
operators; comments; in-built modules and functions; Conditional:
boolean values and operators, conditional (if), alternative (if-else),
case analysis (if-elif-else).

{{{unit}}}
| UNIT III | ITERATION, FUNCTION, STRINGS | 9 |
Iteration: while, for, break, continue, pass; Functions: function
definition, function call, flow of execution, parameters and
arguments, return values, local and global scope, recursion; Strings:
string slices, immutability, string functions and methods, string
module.

{{{unit}}}
| UNIT IV | LISTS, TUPLES | 9 |
Lists: list operations, list slices, list methods, list loop,
mutability, aliasing, cloning lists, list parameters, nested lists,
list comprehension; Tuples: tuple assignment, tuple as return value,
tuple operations.

{{{unit}}}
| UNIT V | DICTIONARIES, FILES | 9 |
Dictionaries: operations and methods, looping and dictionaries,
reverse lookup, dictionaries and lists; Files: Text files, reading and
writing files, format operator, file names and paths; command line
arguments.

\hfill *Total Periods:45*

** COURSE OUTCOMES
After the completion of this course, students will be able to
1. Solve programming problems and express solutions using algorithmic constructs (K3)
2. Develop simple programs using basic constructs and conditional statements (K3)
3. Develop programs using  looping constructs, functions and strings (K3)
4. Use lists and tuples to develop programs (K3)
5. Construct programs using dictionaries and perform Input/Output operations using files (K3)

  
** TEXT BOOKS
1. Karl Beecher, ``Computational Thinking -- A beginner's Guide to
   Problem Solving and Programming'', British Computer Society
   (BCS), 2017.
2. Allen B. Downey, ``Think Python: How to Think Like a Computer
   Scientist'', 2nd edition, Green Tea Press, Shroff/O'Reilly
   Publishers, 2015 (http://greenteapress.com/wp/think-python/)
   

** REFERENCES
1. Ashok Namdev Kamthane, Amit Ashok Kamthane, "Programming and
   Problem Solving with Python", McGraw Hill Education (India) Private
   Limited, 2018.
2. John V Guttag, ``Introduction to Computation and Programming Using
   Python'', MIT Press, 2016.
3. Robert Sedgewick, Kevin Wayne, Robert Dondero, ``Introduction to
   Programming in Python: An Inter-disciplinary Approach'', Pearson
   India Education Services Pvt. Ltd., 2016.
4. Timothy A. Budd, ``Exploring Python'', Mc-Graw Hill Education
   (India) Private Ltd., 2015.
5. Kenneth A. Lambert, ``Fundamentals of Python: First Programs'', 2nd
   Edition, Cengage Learning, 2018.

** CO TO PO/PSO MAPPING
| PO/PSO |  1 |  2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |  1 | 2 |
|--------+----+----+---+---+---+---+---+---+---+----+----+----+----+---|
| CO1    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  2 |   |
| CO2    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  2 |   |
| CO3    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  3 |   |
| CO4    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  3 |   |
| CO5    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  3 |   |
|--------+----+----+---+---+---+---+---+---+---+----+----+----+----+---|
| Score  | 15 | 10 |   |   |   |   |   |   |   |    |    |    | 13 |   |
| Course |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  3 |   |
