* 
:properties:
:author: 
:date: 
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                                  | L | T | P | E |   C |
| UGE2297 | DESIGN THINKING AND ENGINEERING PRACTICES LAB | 0 | 0 | 3 | 0 | 1.5 |
		
** COURSE OBJECTIVES
- To provide exposure to the students with hands on experience on
  various basic engineering practices in Civil, Mechanical, Electrical
  and Electronics Engineering
- To train the students to dismantle, understand the functional /
  aesthetic aspects of the product, prepare the part functional model,
  and to assemble the different engineering components
    
** LIST OF EXPERIMENTS

** GROUP A (CIVIL & MECHANICAL ENGINEERING PRACTICE) 

*I CIVIL ENGINEERING PRACTICE*

/Buildings/:\\
Study of plumbing and carpentry components of residential and industrial buildings - Safety aspects.
/Plumbing Works/:
    1. Study of pipeline joints, its location and functions: valves,
       taps, couplings, unions, reducers, and elbows in household
       fittings.
    2. Preparation of plumbing line sketches for water supply and
       sewage works.
    3. Hands-on-exercise: 
       - Basic pipe connections - Mixed pipe material connection -
         Pipe connections with different joining components.
       - Plumbing with basic connections for washing basin and sink
/Carpentry using Power Tools only/:
    1. Study of the joints in roofs, doors, windows and furniture.
    2. Hands-on-exercise: Wood work, joints by sawing, planning and
       cutting.
       1. Fabrication of different models of pencil box and pen stand.
       2. Fabrication of wooden wall shelf
    3. Demonstration of wood working machinery

*II MECHANICAL ENGINEERING PRACTICE*

/Basic Machining/:
- Drilling Practice (holes of various diameters - steel sheet metal, wood, hylam/plywood sheet)
/Sheet Metal Work/:
- Forming & Bending
- Different type of joints.
  - Fabrication of mobile phone metal stand
  - Fabrication of electrical control panel box
/Design thinking practices/:
To dismantle, understand the functional / aesthetic aspects of the
product, prepare the part functional model, and to assemble the
following components.
- Pedestal Fan head swing mechanism - Reserve mechanism (Two
  wheeler) - Hot Glue gun - Paper clips - Flush tank container
  mechanism - Hand pump - washer Mechanism
    
     
** GROUP B (ELECTRICAL & ELECTRONICS ENGINEERING PRACTICE)
1. Residential house wiring, staircase wiring and tube light wiring with single phase AC two wire system.
2. Energy measurement with RLC Load. 
3. Earth resistance measurement. 
4. Measurement of AC parameters using CRO and half wave and Full wave rectifier.
5. Study of logic gates AND, OR, EX-OR & NOT.
6. Soldering practice -- Components Devices and Circuits -- Using PCB. 

/Design thinking practices/:
1. Assemble a single phase 3 wire circuit for connecting household appliances and explain through schematic diagram
2. Measure the energy consumed by the household appliances and verify it theoretically 
3. Analyze the fault occurring in electrical appliances
4. Design, assemble and test a cell phone charger
5. Design, assemble and test a relay logic to control electrical appliances.
6. Design, assemble and test a dc power supply using PCB
       
\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to   
1. Draw pipeline plan; lay and connect various pipe fittings used in common household plumbing work; Saw; plan; make joints in wood materials used in common household woodwork (K2)
2. Practice machining to make holes on different materials; fabricate sheet metal components (K2)
3. Dismantle, understand the functional / aesthetic aspects of the product, prepare the part functional model of various components (K2)
4. Construct domestic electrical circuits and verify their output parameters (K3)
5. Construct electronics circuits and verify their output (K3)
   
** REFERENCES
1. S Gowri, T Jeyapoovan, ``Engineering Practices Lab Manual'', 5th
   Edition, Vikas Publishing, 2016.
2. V Ramesh Babu, Engineering Practices Laboratory, VRB
   Publications, 2006.

3. Willis H Wagner, Howard "Bud" Smith, Mark W Huth, ``Modern Carpentry'', 12th Edition, 2015
4. P C Sharma, ``Production Technology: Manufacturing Process'', S Chand publisher, 2006
5. Robert W Messler, ``Reverse Engineering: Mechanisms, Structures, Systems & Materials'', McGraw-Hill Education, 2014
6. David W Rongey, ``A Complete Guide to Home Electrical Wiring'', 2013
7. K Jeyachandran, S Natarajan, S Balasubramanian, ``A Primer on Engineering Practices Laboratory'', Anuradha Publications, 2007
   
** CO TO PO/PSO MAPPING
| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---|
| CO1    | 3 | 2 |   | 1 |   |   |   |   | 2 |  1 |    |  1 |   |   |
| CO2    | 3 | 2 |   | 1 |   |   |   |   | 2 |  1 |    |  1 |   |   |
| CO3    | 3 | 2 |   | 1 |   |   |   |   | 2 |  1 |    |  1 |   |   |
| CO4    | 3 | 3 |   | 3 |   |   |   |   | 3 |  1 |    |  1 |   |   |
| CO5    | 3 | 3 |   | 3 |   |   |   |   | 3 |  1 |    |  1 |   |   |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---|
| Course | 3 | 3 |   | 2 |   |   |   |   | 3 |  1 |    |  1 |   |   |
