* 
:properties:
:author: Dr. G. Kalpana and Dr. N. Padmapriya
:date: 
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                        | L | T | P | E | C |
| UMA2455 | PROBABILITY AND STATISTICAL METHODS | 3 | 1 | 0 | 0 | 4 |

** COURSE OBJECTIVES
- To identify the standard distributions and apply them in solving problems.
- To solve problems in joint probabilities and to find correlation between them.
- To perform hypothesis testing using normal, t, F, chi square distribution 
- To evaluate the tests of significance in analysis of variance.
- To calculate the various statistical quality control measurements.

{{{unit}}}
| UNIT I | RANDOM VARIABLES | 12 |
Random variables -- Discrete and continuous random variables --
Moments -- Moment generating functions -- Binomial, Poisson,
Geometric, Uniform, Exponential, and Normal distributions --
Functions of random variable.

{{{unit}}}
| UNIT II | TWO-DIMENSIONAL RANDOM VARIABLES | 12 |
Joint distributions -- Marginal and conditional distributions --
Covariance -- Correlation and linear regression -- Transformation of
random variables -- Central limit theorem (for independent and
identically distributed random variables).

{{{unit}}}
| UNIT III | TESTS OF SIGNIFICANCE | 12 |
Sampling distributions -- Small and large sample test -- Test based on
Normal and t distribution (Single and difference of mean)-- \chi^2 --
Test for goodness of fit, Independence of attributes -- F test for
variance.

{{{unit}}}
| UNIT IV | DESIGN OF EXPERIMENTS | 12 |
Completely randomized design -- Randomized block design -- Latin
square design -- Factorial design.

{{{unit}}}
| UNIT V | 	STATISTICAL QUALITY CONTROL | 12 |
Control charts for measurements (X and R charts) -- Control charts for
attributes (p, c and np charts) -- Tolerance limits -- Acceptance
sampling.

\hfill *Total Periods: 60*

** COURSE OUTCOMES
On successful completion of this course, the student will be able to
1. identify standard distributions and apply them.
2. solve problems in two dimensional random variables and find the correlation between them.
3. identify and apply the suitable testing of hypothesis under normal, t, F and chi square distribution 
4. solve problems in analysis of variance.
5. analyze quality control by applying control chart methods.
6. apply random variables, and design experiments and control charts in
   engineering problems
      
** TEXT BOOKS
1. Milton J S and Arnold J C, ``Introduction to Probability and
   Statistics'', 4th Edition, 3rd Reprint, Tata McGraw Hill, 2014.
2. Johnson R A and Gupta C B, ``Miller and Freund's Probability and
   Statistics for Engineers'', 9th Edition, Pearson Education, 2016.

** REFERENCES
1. Devore J L, ``Probability and Statistics for Engineering and the
   Sciences'', 8th Edition, Thomson Brooks/Cole, International Student
   Edition, 2012.
2. Walpole R E, Myers R H, Myers S L, Ye K, ``Probability and
   Statistics for Engineers and Scientists'', 9th Edition, Pearson
   Education, Asia, 2012.
3. Ross S M, ``Introduction to Probability and Statistics for
   Engineers and Scientists'', 5th Edition, Elsevier, New Delhi, 2014.
4. Spiegel M R, Schiller J, Srinivasan R A, ``Schaum's
   Outline of Theory and Problems of Probability and Statistics'',
   3rd Edition, Tata McGraw Hill, New Delhi, 2004.
5. Gupta S C, Kapoor V K, ``Fundamentals of Mathematical Statistics'',
   12th Edition, Sultan and Chand Company, New Delhi, 2020.

** CO TO PO/PSO MAPPING
| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 1 | 11 | 12 | 1 | 2 |
|--------+---+---+---+---+---+---+---+---+---+---+----+----+---+---|
| CO1    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
| CO2    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
| CO3    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
| CO4    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
| CO5    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
| CO6    | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
|--------+---+---+---+---+---+---+---+---+---+---+----+----+---+---|
| Course | 3 | 2 |   | 1 |   |   |   |   |   |   |    |    | 1 |   |
