* 
:properties:
:author: Dr. J. Bhuvana, Ms. S. Lakshmi Priya
:date: 09-03-2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE      | L | T | P | E | C |
| UCS2402 | OPERATING SYSTEMS | 3 | 0 | 0 | 0 | 3 |


** R2021 CHANGES :noexport:
1. Monitors in Unit II removed.
2. I/O Systems in Unit IV removed.

#+begin_comment
  1. As the course is focused towards fundamental resource handling strategies, advanced techniques suggested like RELRO and ASLR are not included
  2. Since there exists a specific course on security in a higher semester, inclusion of security perspectives for operating systems theory and lab would be too early for second-year students
#+end_comment

#+begin_comment
 1. Unit V - Windows case study included
 2. Windows was added as a comparative study with Linux
 3. Five Course outcomes specified and aligned with units
 4. For lab, suggestive experiments are clearly defined.
#+end_comment

** COURSE OBJECTIVES
- To understand the structure and functions of OS
- To learn about Processes, Threads and Scheduling algorithms
- To understand the principles of concurrency and Deadlocks
- To learn various memory management schemes
- To study disk management and File systems.


{{{unit}}}
|UNIT I | OPERATING SYSTEMS OVERVIEW | 9 |
Computer System Overview: Basic elements -- Instruction execution –
Interrupts -- Memory hierarchy -- Cache memory -- Direct memory access
-- Multiprocessor and multicore organization; Operating System
Overview: Objectives and functions -- Evolution of operating
system;Computer system organization; Operating System Structure and
Operations: System calls -- System programs -- OS generation and
system boot.

{{{unit}}}
|UNIT II | PROCESS MANAGEMENT | 12 |
Processes: Process concept -- Process scheduling -- Operations on
processes -- Interprocess communication; Threads: Overview --
Multithreading models -- Thread issues;  CPU Scheduling: FCFS, SJF, Priority, Roundrobin, Rate Monotonic and EDF
scheduling; Process synchronization -- Critical section problem -- Mutex locks -- Semaphores; Deadlocks -- Avoidance -- Prevention -- Detection and
Recovery.

{{{unit}}}
|UNIT III | MEMORY MANAGEMENT | 8 |
Main Memory: Contiguous memory allocation -- Segmentation -- Paging --
32 and 64 bit architecture Examples; Virtual Memory: Demand paging --
Page replacement algorithms -- Allocation of Frames -- Thrashing.

{{{unit}}}
|UNIT IV | STORAGE MANAGEMENT | 9 |
Mass Storage Structure: Overview -- Disk scheduling and management;
File System Storage: File concepts -- Directory and disk structure --
Sharing and protection; File System Implementation: File system
structure -- Directory structure -- Allocation methods -- Free space
management.

{{{unit}}}
|UNIT V | CASE STUDY | 7 |
Linux Vs Windows: Design principles -- Process management --
Scheduling -- Memory management -- File systems; Mobile OS: iOS and
Android -- Introduction and architecture.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Outline the basic services and functionalities of operating systems (K2)
2. Analyze various scheduling algorithms, and understand process synchronization, deadlock prevention and avoidance schemes (K4)
3. Apply different memory management schemes (K3)
4. Apply various disk management schemes and illustrate the functionalities of file systems (K3)
5. Compare and contrast Linux, Windows and mobile operating systems (K2).

** TEXT BOOKS
1. Abraham Silberschatz, Peter Baer Galvin, Greg Gagne, "Operating
   System Concepts'', 9th Edition, John Wiley and Sons Inc, 2012.
2. Neil Smyth, ``iPhone iOS 4 Development Essentials - Xcode'', 4th
   Edition, Payload media,2011.

** REFERENCES
1. Ramez Elmasri, A Gil Carrick, David Levine, ``Operating Systems A
   Spiral Approach'', Tata McGraw Hill Edition, 2010.
2. Achyut S Godbole, Atul Kahate, ``Operating Systems'', McGraw Hill
   Education, 2016.
3. Andrew S Tanenbaum, ``Modern Operating Systems'', 2nd Edition,
   Pearson Education, 2004.
4. Harvey M Deitel, ``Operating Systems'', 3rd Edition, Pearson
   Education, 2004.
5. Daniel P Bovet, Marco Cesati, ``Understanding the Linux Kernel'',
   3rd edition, O‘Reilly,2005.


** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 2 | 2 |   |   |   |   |   |   |    |    |    | 3 |   |   |
| CO2    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 3 |   |   |
| CO3    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 3 |   |   |
| CO4    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 3 |   |   |
| CO5    | 3 |   |   |   |   |   |   |   |   |    |    |    | 3 |   |   |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Score  | 15| 8 | 2 |   |   |   |   |   |   |    |    |    | 15 |  |   |
| Course | 3 | 2 | 2 |   |   |   |   |   |   |    |    |    |  3 |  |   |


