*  
:properties:
:author: Mr. B. Senthil Kumar and Dr. P. Mirunalini
:date: 
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                | L | T | P | E | C |
| UCS2404 | DATABASE MANAGEMENT SYSTEMS | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. Fifth unit is new unit. All other units are already discussed in AU-2017.
2. For changes, see the individual units.
3. This subject is not offered under M.E syllabus.
4. Five Course outcomes specified and aligned with units.
5. Done.
6. Added CO6 and updated the pos accordingly

** COURSE OBJECTIVES
- To introduce the fundamentals of database systems and conceptual
  modeling
- To learn SQL and relational model
- To learn database programming and relational database design
- To explore the fundamental concepts of transaction processing,
  concurrency control and recovery techniques
- To explain Distributed and NOSQL databases.


{{{unit}}}
|UNIT I | DATABASE SYSTEM CONCEPTS AND CONCEPTUAL MODELING | 8 |
Characteristics of database -- Database users -- Data models, Schemas
-- Three-schema architecture -- Database system environment --
Centralized and client/server DBMS architectures -- Data modeling
using ER model -- Enhanced-ER model.

{{{unit}}}
|UNIT II | RELATIONAL MODEL AND SQL | 11 |
Relational Model: Concepts -- Constraints -- Update operations --
Constraint violations; Relational Algebra; Basic SQL: Data Definition
-- SQL constraints -- Basic retrieval queries -- Insert, delete and
update commands -- Schema modification; More SQL: dealing NULL --
Tuples, Set/Multiset comparisons -- Correlated nested -- EXISTS
function -- SQL Renaming -- JOIN and Outer JOINs -- Aggregate
functions -- Grouping.

#+begin_comment

#+end_comment

{{{unit}}}
| UNIT III | DATABASE PROGRAMMING AND DESIGN | 10 |
Triggers -- Views; Database Programming Techniques: Overview and
Issues -- Embedded SQL -- JDBC -- Database Stored Procedures and
SQL/PSM ; Design guidelines -- Functional dependencies -- First,
second and third Normal Forms -- Boyce-Codd Normal Forms; FD:
Inference rules -- Minimal cover; ER-to-relational mapping.

{{{unit}}}
| UNIT IV | TRANSACTION, CONCURRENCY AND RECOVERY | 8 |
Transaction Processing: Concepts -- ACID properties -- schedules --
serializability; Concurrency control: Two-phase locking technique --
Timestamp Ordering; Recovery: Concepts -- Deferred update -- Immediate
update.

{{{unit}}}
| UNIT V | DISTRIBUTED AND NOSQL DATABASES | 8 |
Distributed Database Concepts -- Data fragmentation and Replication -- 
Allocation techniques; Introduction to NOSQL Systems -- The CAP Theorem 
-- Document-Based NOSQL Systems and MongoDB -- Column-based NOSQL systems.

#+begin_comment
Added a new topic, distributed databases and removed the key-value and graph-based NOSQL
databases.
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Explain the database concepts and apply ER models for a database applications (K3)
2. Apply SQL for relational data model (K3)
3. Apply database programming techniques , database design theory and normalization(K3)
4. Apply concurrency control and recovery mechanisms for transaction processing systems (K3)
5. Explain the concepts of Distributed and NOSQL databases (K2)
6.  Design the database schema by analyzing the data for a real time application with documentation (K6).

** TEXT BOOKS 
1. Ramez Elmasri, Shamkant B Navathe, ``Fundamentals of Database
   Systems'', 7th Edition, Pearson, 2016.
2. Raghu Ramakrishnan, `` Database Management Systems'', 4th Edition,
   Tata McGraw Hill, 2010.


** REFERENCES
1. Jeffrey D Ullman, Jennifer Widom, ``A First Course in Database
   Systems'', 3rd Edition, Pearson Education, 2014.
2. S Sumathi, S Esakkirajan, `` Fundamentals of Relational Database
   Management Systems '', (Studies in Computational Intelligence),
   Springer-Verlag, 2007.
3. Abraham Silberschatz, Henry F Korth, S Sudharshan, ``Database
   System Concepts'', 6th Edition, Tata McGraw Hill, 2011.
4. Thomas M Connolly, Carolyn E Begg, "Database Systems - A Practical Approach 
   to Design, Implementation and Management", 6th edition, 2015, Global 
   Edition, Pearson. 
5. Hector Garcia-Molina, Jeffrey D Ullman, Jennifer Widom, "Database
   Systems:The Complete Book", 2e, Pearson.

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 2 |   |   |   |   |   |   |   |   |   |     |  2 |   |  |
| CO2    | 3 | 2 |   |   |   |   |   |   |   |   |   |     |    |   |  |
| CO3    | 3 | 2 |   |   |   |   |   |   |   |   |   |     | 2  |   |  |
| CO4    | 3 | 2 |   |   |   |   |   |   |   |   |   |     | 2  |   |  |
| CO5    | 3 | 2 |   |   |   |   |   |   |   |   |   |     | 2  |   |  |
| CO6    |   | 3 | 3 |   |   |   |   |   | 3 | 3 |   |     | 2  |   |  |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course |15 | 13| 3 |   |   |   |    |  | 3 | 3  |  |     |  8 |  |   |
| Score | 3  | 3 | 3 |   |   |   |    |  | 3 | 3  |  |     |  2 |  |   |



