* 
:properties:
:author: Dr. A. Beulah and Dr. S.Kavitha
:date: 15-03-2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE          | L | T | P | E | C |
| UCS2603 | THEORY OF COMPUTATION | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
CO-PO mapping later

** COURSE OBJECTIVES
- To learn the mathematical notations and construct finite automata of the given language
- To understand and infer the relationship of finite automate and regular expressions
- To understand the language hierarchy, relationship between context free grammar and its language and to construct a PDA of CFG.
- To understand Turing machines and their programming capability
- To infer the knowledge of undecidable problems.

#+begin_comment
1. From the previous syllabus Unit 1 is splitted into two units.
2. This subject is not offered under M.E syllabus.
3. One more CO is inculded and CO's are modified to align with units.
#+end_comment

{{{unit}}}
|UNIT I | MATHEMATICAL INTRODUCTION AND FINITE AUTOMATA   | 8 |
Basic Mathematical Notation and Techniques: Introduction to Formal
Proof -- Additional Forms of Proof -- Inductive Proofs; Finite
Automata (FA): Deterministic Finite Automata (DFA) --
Non-deterministic Finite Automata (NFA) -- Finite automata with
epsilon transitions -- Equivalence of FAs.
 

{{{unit}}}
|UNIT II | REGULAR LANGUAGES  | 9 |
Regular Expressions and Languages: Regular expressions -- Finite
automata and regular expressions; Properties of Regular Languages:
Proving languages not to be regular -- Closure properties of regular
languages -- Equivalence and Minimization of Automata.

{{{unit}}}
|UNIT III | CONTEXT FREE LANGUAGES AND PUSHDOWN AUTOMATA | 10 |
Chomsky's Hierarchy of Languages; Context-Free Grammar and Languages:
Context-Free Grammar (CFG) -- Parse trees -- Ambiguity in grammars and
languages; Normal Forms for Context Free Grammars: Elimination of
Useless Symbols, epsilon and unit productions -- Chomsky Normal Form
(CNF) -- Greibach Normal Form (GNF).

Pushdown Automata (PDA): Definition of the Pushdown automaton -- The
languages of a PDA -- Equivalence of PDAs and CFGs -- Deterministic
Pushdown automata; Pumping Lemma for Context Free Languages.

{{{unit}}}
|UNIT IV | TURING MACHINES  | 9 |
The Turing Machine -- Programming Techniques for Turing Machines:
Storage in the State -- Multiple Tracks -- Subroutines; Extensions to
the Basic Turing Machine.

{{{unit}}}
|UNIT V | UNDECIDABILITY | 9 |
Undecidablity: Language that is not Recursively Enumerable (RE) --
Undecidable problem that is RE -- Undecidable problems about Turing
machines -- Post's Correspondence Problem (PCP).

# \hfill *Tutorial: 15*
\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Solve the mathematical proofs related to compuation and Construct
   finite automata for the given language (K3)
2. Analyze the relationship between Finite Automata and regular
   expression (K4)
3. Distinguish the type of grammar, relationship between language to
   context free grammar and construction of PDA for the CFG (K4)
4. Construct Turing machine for the given Language (K3)
5. Explain the Decidability or Undecidability of various problems and
   make use of it (K3).
# - Design a suitable model for the given application (K6)

** TEXT BOOKS 
1. Hopcroft J E, Motwani R, Ullman J D, ``Introduction to Automata
   Theory, Languages and Computations'', Pearson Education, 3rd
   Edition, 2008.

** REFERENCES
1. Harry R Lewis, Christos H Papadimitriou, ``Elements of the Theory
   of Computation'', Prentice Hall of India, 2nd Edition, 2003.
2. Peter Linz, ``An Introduction to Formal Language and Automata'',
   Narosa Publishers, 3rd Edition, 2002.
3. Mishra K L P, Chandrasekaran N, ``Theory of Computer Science --
   Automata, Languages and Computation'', Prentice Hall of India, 3rd
   Edition, 2004.

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 3 | 1 | 2 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |
| CO2    | 2 | 3 | 2 | 2 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |
| CO3    | 2 | 3 | 2 | 2 | 0 | 0 | 0 | 1 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |
| CO4    | 2 | 3 | 1 | 2 | 0 | 0 | 0 | 1 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |
| CO5    | 2 | 3 | 1 | 2 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  1 | 1 | 0 | 0 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 2 | 2 | 0 | 0 | 0 | 1 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |

# | Score          |    | 13 | 15 | 7 | 10 | 0 | 0 | 0 | 2 | 0 |  0 |  0 |  5 | 9 | 0 | 0 | 
