* 
:properties:
:author: Ms. R. Priyadharsini and Ms. P. Mirunalini
:date: 09.03.2021  
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                  | L | T | P | E | C |
| UCS2523 | IMAGE PROCESSING AND ANALYSIS | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. Added case study in units 2,4 & 5
2. Modified CO5 from K3 to K4
3. CO6 is added to map the soft POs and mapping done accordingly.

#+begin_comment
- 1. Almost the same as EC8093  DIGITAL IMAGE PROCESSING in AU 2017
- 2. Change in Unit V (see the comment below unit V)
- 3. Unit - II in PCP1279(M.E. CSE Image Processing and Analysis)is
     split into Unit- II and III
     Image segmentation and Feature analysis methods in Unit- III of PCP1279 are moved to Unit - IV and 
     Unit - V respectively.
     The topic object recognition is added in Unit - V
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable.
#+end_comment

** COURSE OBJECTIVES
- To be familiar with digital image fundamentals
- To understand the basics of simple image enhancement techniques in
  Spatial and Frequency domain
- To learn the concepts of degradation function and restoration
  techniques
- To study image segmentation and representation techniques
- To be familiar with object recognition methods.

{{{unit}}}
|UNIT I | DIGITAL IMAGE FUNDAMENTALS | 9 |
Introduction to Digital Image Processing: Components -- Image sensing
and acquisition -- Image sampling and quantization; Relationships
between Pixels; 2D Mathematical Preliminaries: Array vs matrix
operations -- Linear vs nonlinear operations -- Arithmetic -- Logical
-- Statistical -- Spatial operations-- Vector and matrix operations.

{{{unit}}}
|UNIT II | IMAGE ENHANCEMENT | 9 |
Spatial Domain: Gray level transformations -- Histogram processing--
Basics of Spatial Filtering -- Smoothing and sharpening spatial
filtering; Frequency Domain: Introduction to fourier transform -- The 2D convolutional theorem--
Smoothing and Sharpening Frequency Domain Filters: Ideal --
Butterworth -- Gaussian filters; Homomorphic Filtering; Case Study: Medical image enhancement.

{{{unit}}}
|UNIT III | IMAGE RESTORATION | 9 |
Image Restoration: Degradation model; Noise models; Restoration in the
Presence of Noise using Spatial Filtering: Mean filters -- Order
statistics -- Adaptive filters; Periodic Noise Reduction by Frequency
Domain Filtering: Band reject filters -- Band pass filters -- Notch
filters -- Optimum notch filtering;Estimating the degradation function-- Inverse filtering; Wiener
filtering.

{{{unit}}}
|UNIT IV | IMAGE SEGMENTATION | 9 |
Edge Detection: Techniques -- Edge linking via Hough transform; Thresholding:
Intensity thresholding -- Otsu's thresholding; Region Based
Segmentation: Region growing -- Region splitting and merging;
Morphological Processing: Erosion and dilation; Segmentation by
Morphological Watersheds: Basic concepts -- Dam construction --
Watershed segmentation algorithm; Case Study: License plate localization.

{{{unit}}}
|UNIT V | FEATURE ANALYSIS AND OBJECT RECOGNITION | 9 |
Boundary representation -- Boundary Descriptors;
Regional descriptors -- Texture; Relational descriptors; Object
Recognition: Patterns and pattern classes; Recognition based on
decision theoretic methods; Case Study: Model based Tracking of animals. 

#+begin_comment
Removed: Image compression
Added: Case Study for Image recognition
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Explain the basics and fundamentals of digital image processing,
   such as digitization, sampling, quantization (K2)
2. Apply the techniques of smoothing, sharpening and
   enhancement in both spatial and frequency domain (K3)
3. Explain the restoration concepts and filtering techniques (K2)
4. Identify the segmentation methods and apply in real time
   applications (K3)
5. Analyse the feature extraction and object recognition methods (K4)
6. Develop real time application in teams by using image processing
   and analysis techniques with a clear documentation of the approach
   (K4).

   
** TEXT BOOKS
1. Rafael C Gonzalez, Richard E Woods, ``Digital Image Processing'',
   Pearson, 3rd Edition, 2010.
2. Anil K Jain, ``Fundamentals of Digital Image Processing'',
   Pearson, 2002.
   
** REFERENCES
1. Kenneth R Castleman, ``Digital Image Processing'', Pearson, 2006.
2. Rafael C Gonzalez, Richard E Woods, Steven Eddins, ``Digital Image
   Processing Using MATLAB'', Pearson Education, Inc., 2011.
3. S Sridhar, ``Digital Image Processing'', 2nd Edition, Oxford
   University, 2016.
4. William K Pratt, ``Digital Image Processing'', John Wiley, New
   York, 2002.
5. Milan Sonka, Roger Boyle, Vaclav Hlavac, ``Image Processing,
   Analysis and Machine Vision'', Brookes/Cole, Vikas Publishing
   House, 2nd edition, 1999.


** CO TO PO/PSO MAPPING 

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 2 | 2 | 1 | 1 | 1 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO2    | 3 | 2 | 2 | 2 | 1 | 1 | 0 | 0 | 1 |  1 |  0 |  0 | 3 | 2 | 1 |
| CO3    | 2 | 2 | 1 | 1 | 1 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO4    | 3 | 2 | 2 | 2 | 1 | 0 | 1 | 0 | 1 |  1 |  0 |  0 | 3 | 2 | 1 |
| CO5    | 3 | 2 | 2 | 2 | 1 | 0 | 0 | 0 | 1 |  1 |  0 |  0 | 3 | 2 | 1 |
| CO6    | 2 | 2 | 2 | 1 | 1 | 1 | 1 | 1 | 3 |  2 |  0 |  1 | 2 | 3 | 2 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 2 | 2 | 2 | 1 | 1 | 1 | 1 | 1 |  1 |  0 |  1 | 3 | 2 | 1 |

# | Score          | 15 | 12 | 10 | 9 | 6 | 2 | 2 | 1 | 6 |  5 |  0 |  1 | 15 | 9 | 5 |
