*  
:properties:
:author: Dr. A. Chamundeswari and Dr. S. Saraswathi
:date:  04-03-2021 09-03-2021 10-03-2021 17-3-2021 29-03-2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE    | L | T | P | E | C |
| UCS2624 | CYBER FORENSICS | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
- Complete Syllabus changed based on a new text book.
- 1-6 : 1  
- 7-12: 2
- 13-18: 3

** COURSE OBJECTIVES
- To learn computer forensics and understand incident response
- To know the methods to collect and store digital evidence
- To understand the approaches to analyse and validate data
- To explore the malware and threat intelligence
- To learn mobile forensics concepts 

{{{unit}}} 
| UNIT I | 	FUNDAMENTALS | 9 |
Understanding Incident Response : The incident response process -- The
incident response charter --The incident response plan -- The incident
response playbook -- Testing the incident response framework;
Managing Cyber Incidents: Investigating incidents -- Incorporating
containment strategies -- Getting back to normal – eradication and
recovery; Fundamentals of Digital Forensics -- Legal aspects --
Digital forensics fundamentals -- The digital forensics process --
Digital forensic lab.
 
#+begin_comment
...Text Book 1 : Chapter 1,2,3 
#+end_comment

{{{unit}}}

|UNIT II | EVIDENCE ACQUISITION   | 9 |
Collecting Network Evidence : An overview of network evidence --
Firewalls and proxy logs --NetFlow -- Packet captures -- Wireshark --
Evidence collection; Acquiring Host-Based Evidence Preparation : Order
of volatility -- Evidence acquisition -- Acquiring volatile memory ;
Forensic Imaging : Understanding forensic imaging -- Imaging tools --
Preparing a stage drive -- Using write blockers -- Imaging techniques.

#+begin_comment
...Text Book 1 : Chapter 4,5,6
#+end_comment  

{{{unit}}}
|UNIT III | ANALYZING EVIDENCE | 9 |
Analyzing Network Evidence : Network evidence overview -- Analyzing
firewall and proxy logs ; Analyzing System Memory : Memory analysis
overview -- Memory analysis methodology ; Analyzing System Storage :
Forensic platforms -- Autopsy -- MFT analysis -- Registry analysis;
Analyzing Log Files : Understanding Windows logs ; Writing the
Incident Report : Documentation overview.
 
#+begin_comment
 ...Text Book 1 : Chapter 7,8,9,10, 11
#+end_comment

{{{unit}}}
|UNIT IV |  MALWARE AND THREAT INTELLIGENCE | 9 |
Malware Analysis for Incident Response : Malware classifications --
Malware analysis overview -- Analyzing malware -- Dynamic analysis --
Leveraging Threat Intelligence -- Understanding threat intelligence --
Threat intelligence methodology -- Threat intelligence sources --
Threat intelligence platforms Using threat intelligence.
  
#+begin_comment
  ...Text Book 1 : Chapter 12, 13
#+end_comment
 
{{{unit}}}
|UNIT V | MOBILE FORENSICS  | 9 |
Introduction to Mobile Forensics : Why do we need mobile forensics? --
Mobile forensics -- The mobile phone evidence extraction process --
Practical mobile forensic approaches ; Parsing Third-Party Application
Files : Third-party application overview -- Encoding versus encryption
-- Application data storage -- Forensic methods used to extract
third-party application data.
 
#+begin_comment
 ...Text Book 2 : Chapter 1, 13 
#+end_comment


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Summarize the basics of computer forensics (K2)
2. Apply different computer forensic tools to collect data (K3)
3. Apply tools to analyze and validate forensic data (K5)
4. Classify the malware and threat intelligence (K2)  
5. Apply forensic tools on mobile data (K3).


** TEXT BOOKS 
1. Gerard Johansen, ``Digital Forensics and Incident Response'',
   Second Edition, Packt Publishing, 2020.
2. Rohit Tamma, Oleg Skulkin, Heather Mahalik, Satish Bommisetty,
   ``Practical Mobile Forensics'', Third Edition, Packt
   Publishing, 2018.

** REFERENCES 
1. Nelson, Phillips, Enfinger, Steuart, ``Computer Forensics and
   Investigations'', Cengage Learning, India Edition, 2008.
2. John R Vacca, ``Computer Forensics'', Cengage Learning, 2005.
3. Marjie T Britz, ``Computer Forensics and Cyber Crime: An
   Introduction'', 3rd Edition, Prentice Hall, 2013.
4. Marcella Jr, Albert, and Doug Menendez, ``Cyber Forensics: a Field
   Manual for Collecting, Examining, and Preserving Evidence of
   Computer Crimes'', Auerbach Publications, 2007.


** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO2    | 3 | 2 |   |   | 1 |   |   |   |   |    |    |    | 3 |   |   |
| CO3    | 3 | 3 |   |   | 1 |   |   |   |   |    |    |  2 | 3 |   | 2 |
| CO4    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO5    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Score  |15 |11 |   |   | 2 |   |   |   |   |    |    |  2 |12 |   | 2 |
| Mapping| 3 | 3 |   |   | 1 |   |   |   |   |    |    |  2 | 3 |   | 2 |
