* 
:properties:
:author: Dr. K. Vallidevi and Dr. S. Manisha
:date: 29.03.2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                        | L | T | P | E | C |
| UCS2723 | OBJECT ORIENTED ANALYSIS AND DESIGN | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. No change in units from R-2018
2. The Course ourcomes are rephrased and aligned with the units. And CO-PO-PSO Mappings are done as per the expert's suggestions.
3. Sixth Course outcome specified and aligned with units
4. No change of content from R-2018
5. Reference book edition is changed for "Design patterns: Elements of Reusable Object Oriented Software", Pearson Education, 2015.


** COURSE OBJECTIVES
- To understand and differentiate Unified Process from other approaches 
- To understand object-oriented software design using UML's static diagrams
- To understand software modeling using the UML's dynamic diagrams
- To learn improving software design with design patterns
- To learn testing the software with its requirements specification.

{{{unit}}}
|UNIT I | DEVELOPMENT PROCESS & USE-CASE DIAGRAM (STATIC)  | 9 |
Introduction to OOAD with OO Basics -- Unified process -- UML diagrams
-- Use case -- Case study -- The Next Gen POS system, Inception -- Use
case modelling -- Relating use cases -- Include, extend and
generalization -- When to use use-cases.

{{{unit}}}
|UNIT II | UNIFIED PROCESS & CLASS DIAGRAM (STATIC)		| 9 |
Class diagram -- Elaboration -- Domain model -- Finding conceptual
classes and description classes -- Associations -- Attributes --
Domain model refinement -- Finding conceptual class hierarchies --
Aggregation and composition -- Relationship between sequence diagrams
and use cases -- When to use class diagrams.

{{{unit}}}
|UNIT III | DYNAMIC & IMPLEMENTATION DIAGRAMS  | 9 |
Dynamic Diagrams: UML interaction diagrams -- System sequence diagram
-- Collaboration diagram -- When to use communication diagrams --
State machine diagram and modelling -- When to use state diagrams --
Activity diagram -- When to use activity diagrams.

Implementation Diagrams: UML package diagram -- When to use package
diagrams -- Component and deployment diagrams -- When to use component
and deployment diagrams.

{{{unit}}}
|UNIT IV | DESIGN PATTERNS | 9 |
Designing objects with responsibilities -- Creator -- Information
expert -- Low coupling -- High cohesion -- Controller design patterns
-- Creational -- Factory method -- Structural -- Bridge -- Adapter --
Behavioural -- Strategy -- Observer -- Applying GoF design patterns --
Mapping design to code.

{{{unit}}}
| UNIT V | TEST DRIVEN DEVELOPMENT AND REFACTORING | 9 |
Object oriented methodologies -- Software quality assurance -- Impact
of object orientation on testing -- Develop test cases and test plans.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
On successful completion of this course, the student will be able to 
CO 1: Model the given problem  using Use case diagrams (K3) 
CO 2: Apply OO concepts for project development (K3) 
CO 3: Choose appropriate UML diagrams for modeling  user requirements (K5) 
CO 4: Make use of the design patterns to transform UML based software design into pattern-based design (K3) 
CO 5:   Develop test cases and test plans for object oriented software   (K3).


** TEXT BOOKS
1. Larman, Craig, ``Applying UML and Patterns'', Pearson Education
   Asia, 2008.
2. Ali Bahrami, ``Object Oriented Systems Development'', McGraw Hill
   International Edition, 1999.

** REFERENCES
1. Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides, ``Design
   patterns: Elements of Reusable Object Oriented Software'', Pearson
   Education, 2015.
2. Martin Fowler, ``UML Distilled: A Brief Guide to the Standard
   Object Modeling Language'', 3rd edition, Addison Wesley, 2003.
3. Booch, G, Jacobson I, Rumbaugh J, ``The Unified Modeling Language
   User Guide'', Addison Wesley, 2008.
4. Roger S Pressman, ``Software Engineering -- A Practitioner's
   Approach'', 7th edition, 2010.
5. Aditya P Mathur, ``Foundations of Software Testing -- Fundamental
   Algorithms and Techniques'', Dorling Kindersley (India) Pvt. Ltd.,
   Pearson Education, 2008.
   
** CO TO PO/PSO MAPPING
| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 2 | 2 |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO2    | 3 | 2 | 2 |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO3    | 3 | 3 | 3 |  |  |  |  |  |  | 2 |   |   | 2 |  |  |
| CO4    | 3 | 2 | 2 |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO5    | 3 | 3 | 2 |  |  |  |  |  |  |   |   |   | 2 |  |  |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 3 |  |  |  |  |  |  | 2 |   |   | 2 |  |  |

# | Score | 15 | 12 | 11 |  |  |  |  |  |  | 2 |  |  |  |  |  |

