* 
:properties:
:author: Dr. R.S.Milton and Ms. S. Angel Deborah
:date: 18-03-2021
:end:


#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE           | L | T | P | C |
| UCS2721 | BAYESIAN DATA ANALYSIS | 3 | 0 | 0 | 3 |


** COURSE OBJECTIVES
- To know the fundamental concepts of probability theory, machine learning and statistics
- To explore One-parameter model, normal model and multivariate model
- To analyse data using hierarchial modeling and non parametric models
- To analyse the difference between non-bayesian model with bayesian model.
- To solve real time problems using bayesian computation.

{{{unit}}}
| UNIT I | BASICS OF PROBABILITY THEORY, MACHINE LEARNING AND STATISTICS | 9 |
Introduction:Bayes -- Estimating Probability of a Rare Event --
Building a Predictive Model; Probability:Events -- Partitions -- Bayes
Rule -- Independene -- Random Variable -- Joint Distribution; Bayesian
Inference in Applied Statistics.


{{{unit}}}
| UNIT II | ONE PARAMETER MODELS AND NORMAL MODEL  9 |
The Binomial Model: Inference -- Confidence Region; The Poisson model
-- Posterior Inference; Exponential Families and Conjugate Priors; The
Normal Model: Inference for the Mean, Conditional on the Variance --
Joint Inference for the Mean and Variance -- Prior Specification Based
on Expectations -- The Normal Model for Non-Normal Data; The
Multivariate Normal Model.

{{{unit}}}
|UNIT III | GROUP COMPARISONS AND HIERARCHICAL MODELING| 9 |
Group Comparisons: Comparing Two Groups -- Comparing Multiple Groups
-- Exchangeability and Hierarchical Models; The Hierarchical Normal
Model: Posterior Inference -- Hierarchical Modeling of Means and
Variances -- Analysis of Math Score Data.

{{{unit}}}
|UNIT IV |  LINEAR REGRESSION AND NON PARAMETRIC MODEL | 9 |
The Linear Regression Model: Least Squares Estimation for the Oxygen
Uptake Data; Bayesian Estimation for a Regression Model: A
Semiconjugate Prior Distribution -- Default and Weakly Informative
Prior Distributions; Model Selection: Bayesian Model Comparison --
Gibbs Sampling and Model Averaging; Non-Parametric Model: Gaussian
Process Models -- Finite Mixture Models.

{{{unit}}}
| UNIT V | BAYESIAN COMPUTATION | 9 |
Monte Carlo approximation: The Monte Carlo Method -- Posterior
Inference for Arbitrary Functions -- Sampling from Predictive
Distributions -- Posterior Predictive Model Checking; Posterior
Approximation with the Gibbs Sampler: A Semiconjugate Prior
Distribution -- Discrete Approximations -- Gibbs Sampling --
Metropolis-Hastings Algorithm and Gibbs Sampler.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Summarize the basics of theory, machine learning and statistics(K2)
- Apply One-parameter model to develop a system (K3)
- Analysing data using hierarchical model (K4)
- Compare non-bayesian model with bayesian model (K4)
- Apply various Bayesian computation techiniques to solve a problem (K3)
- Solve a real time problem using any bayesian approach with clear documentation (K4)


      
** TEXT BOOKS
1. Peter D Hoff, ``A first course in Bayesian Statistical Methods'',
   Springer, 2009.


** REFERENCES
1. Andrew Gelman, John B Carlin, Hal S. Stern HS, David B Dunson, Aki
   Vehtari, Dolland B.Rubin, ``Bayesian data analysis'', third
   edition, CRC press, 2013.
2. Richard McElreath, ``Statistical Rethinking'', second edition, CRC
   press, 2020.
3. John Kruschke, ``Doing Bayesian Data Analysis: A Tutorial with R,
   JAGS, and Stan'', second edition, Academic Press,2014


** CO TO PO/PSO MAPPING
#+NAME: co-po-mapping
| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 2 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 |  1 |  0 |  1 | 1 | 0 | 0 |
| CO2    | 3 | 3 | 3 | 2 | 2 | 0 | 0 | 1 | 1 |  1 |  0 |  2 | 3 | 0 | 2 |
| CO3    | 3 | 3 | 3 | 2 | 2 | 0 | 0 | 1 | 1 |  1 |  0 |  2 | 3 | 0 | 0 |
| CO4    | 3 | 3 | 3 | 2 | 2 | 0 | 0 | 1 | 0 |  1 |  0 |  2 | 3 | 0 | 0 |
| CO5    | 3 | 3 | 3 | 2 | 2 | 0 | 0 | 1 | 1 |  1 |  0 |  2 | 3 | 0 | 2 |
| CO6    | 3 | 3 | 3 | 3 | 3 | 1 | 1 | 1 | 2 |  3 |  0 |  2 | 3 | 2 | 2 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 3 | 2 | 2 | 1 | 1 | 1 | 1 |  2 |  0 |  2 | 3 | 1 | 1 |

# | Score | 17 | 16 | 16 | 12 | 12 | 1 | 1 | 6 | 5 | 8 | 0 | 9 | 16 | 2 | 6 |
