* 
:properties:
:author: Ms. S. Lakshmi Priya and Dr. N. Sujaudeen
:date: 24-03-21
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE            | L | T | P | E | C |
| UCS2742 | GRAPHICS AND MULTIMEDIA | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. Bezier curves and surfaces removed to concentrate more on 3D transformations and projections
2. Unit IV & V differ from AU2017. 
3. Unit I - Moved Topics on "Illumination and color Models" to Unit IV.Random and Raster scan systems are added as introductory topics.
   Unit III - Spline representations, Bezier curves and surfaces and B splines are removed from spline representaions topic,  Visible surface detection methods removed.
   Unit IV - Instead of Multimedia introduction, changed to Illumination models and added Animation. 
   Unit V - Has 3 1/2 important chapters from prescribed textbook as opposed to 8 chapters given as Unit 4 and 5 in AU2017 .
4. Not Applicable
5. Five Course outcomes specified and aligned with units
6. For Lab, suggestive experiments are clearly defined.


** COURSE OBJECTIVES
- To gain knowledge on different display devices and its working principles
- To understand the 2D and 3D dimensional graphics representation and object transformations
- To understand illumination principles and color models used in output devices
- To understand basic concepts of multimedia
- To explore Blender graphics tool and design animations.


{{{unit}}}
|UNIT I | DISPLAY SYSTEMS AND OUTPUT PRIMITIVES | 8 |
Introduction to computer graphics -- Applications; Overview of
graphics systems: Video display devices -- Raster scan systems --
Random scan systems; Output primitives: Points and lines -- Loading the
frame buffer -- Line drawing algorithms: DDA and Bresenham's line
drawing algorithms -- Circle and ellipse generating algorithms -- Pixel
addressing and object geometry.

{{{unit}}}
|UNIT II | TWO DIMENSIONAL GRAPHICS | 9 |
Two dimensional geometric transformations: Basic transformations --
Matrix representations and homogeneous coordinates -- Composite
transformations; Two dimensional viewing: Viewing pipeline -- viewing
coordinate reference frame -- Window to viewport coordinate
transformation -- Clipping operations: Point and text clipping -- Line
and polygon clipping algorithms.

{{{unit}}}
|UNIT III | THREE DIMENSIONAL GRAPHICS | 10 |
Three dimensional concepts; Three dimensional object representations:
Polygon surfaces -- Polygon tables -- Plane equations -- Polygon
meshes -- Curved lines and surfaces -- Quadratic surfaces-- Blobby
objects; Three Dimensional Geometric and Modeling Transformations: Translation --
Rotation -- Scaling -- Composite transformations; Three Dimensional
Viewing: Viewing pipeline -- Viewing coordinates -- Projections --
View volumes -- Clipping.

{{{unit}}}
|UNIT IV | ILLUMINATION MODELS AND ANIMATION | 8 |
Light sources -- Basic illumination models: Ambient, Diffuse, Specular
Components of the Phong model; Color Models: Properties of light --
Standard primaries and chromaticity diagram -- RGB, YIQ, CMY, HSV and
HLS color models; Computer Animation: Design of animation sequences --
Keyframe systems -- Motion specifications.

{{{unit}}}
|UNIT V | MULTIMEDIA | 10 |
Multimedia Systems Design: Multimedia elements -- Multimedia
applications -- Multimedia systems architecture -- Defining objects for
multimedia systems -- Multimedia data interface standards; Compression
and decompression; Data and File Format Standards; Hypermedia
Messaging; Case Study -- Blender Graphics: Fundamentals -- Drawing
Basic Shapes -- Modelling -- Shading & textures.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Apply the algorithms to manipulate output primitives such as line,
   circle, ellipse (K3)
2. Apply transformations, representations and clipping on 2D
   objects and map window to viewport transformations (K3)
3. Apply three Dimensional concepts like representations, geometric
   transformations, and projections (K3)
4. Demonstrate the working of different illumination and color models
   used to render an animation scene (K2)
5. Compare different types of multimedia file formats, compression
   techniques and apply transformation algorithms in Blender to create
   animation sequences (K3).

** TEXT BOOKS
1. Donald Hearn, Pauline Baker M, ``Computer Graphics'', Prentice
   Hall, New Delhi, 2007. 
2. Andleigh P K, Kiran Thakrar, ``Multimedia Systems and
   Design'', PHI, 2003. 

** REFERENCES
1. Foley, Vandam, Feiner, Hughes, ``Computer Graphics: Principles
   and Practice'', 2nd Edition, Pearson Education, 2003.
2. Jeffrey McConnell, ``Computer Graphics: Theory into Practice'',
   Jones and Bartlett Publishers, 2006.
3. Hill F S Jr, ``Computer Graphics'', Maxwell Macmillan, 1990.
4. Peter Shirley, Michael Ashikhmin, Michael Gleicher, Stephen R
   Marschner, Erik Reinhard, KelvinSung, AK Peters, ``Fundamentals
   of Computer Graphics'',CRC Press, 2010.
5. https://www.blender.org/support/tutorials/

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 3 | 3 | 3 | 2 | 0 | 0 | 0 | 0 |  0 |  0 |  2 | 3 | 0 | 0 |
| CO2    | 3 | 3 | 2 | 2 | 2 | 0 | 0 | 0 | 0 |  0 |  0 |  2 | 3 | 0 | 0 |
| CO3    | 3 | 3 | 2 | 2 | 2 | 0 | 0 | 0 | 0 |  0 |  0 |  2 | 3 | 0 | 0 |
| CO4    | 2 | 3 | 1 | 2 | 2 | 0 | 0 | 0 | 0 |  0 |  0 |  2 | 3 | 0 | 0 |
| CO5    | 3 | 3 | 3 | 3 | 3 | 0 | 0 | 0 | 1 |  2 |  0 |  2 | 3 | 1 | 1 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 3 | 3 | 3 | 0 | 0 | 0 | 1 |  1 |  0 |  2 | 3 | 1 | 1 |

# | Score | 14 | 15 | 11 | 12 | 11 | 0 | 0 | 0 | 1 | 2 | 0 | 10 | 15 | 1 | 1 |
