* 
:properties:
:author: Dr. V. S. Felix Enigo and Dr. G. Raghuraman
:date: 19/3/21
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                             | L | T | P | E | C |
| UCS2741 | SOCIAL NETWORK ANALYSIS AND APPLICATIONS | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
Modification
  - Course Objectives changed
  - Course Outcome Changed
  - CO-PO Mapping Changed
  - 3 outcomes are made K3 level
  - Text books Versions updated


** COURSE OBJECTIVES
- Understand the fundamentals of social network analysis
- Representing formally the social networks 
- Be acquainted with the working of various community detection algorithms
- Learn to analyze social networks using SNA tools 
- Learn to do visualization for social networks using Visualization tools

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Social Network Analysis: Development of social network analysis -- Key
concepts and measures in network analysis -- Electronic Sources for
Network Analysis: Electronic discussion networks -- Blogs and online
communities -- Web-based networks -- Social Network Data: Introduction --
Boundary specification and sampling -- Types of networks -- Network data --
Measurement and collection.

{{{unit}}}
|UNIT II | MATHEMATICAL REPRESENTATION OF SOCIAL NETWORKS | 9 |
Notations for Social Networks: Graph theoretic notations -- Sociometric
notations -- Algebraic notations -- Two sets of actors -- Graph and
matrices.

{{{unit}}}
|UNIT III | COMMUNITY DETECTION METHODOLOGIES, APPLICATIONS | 9 |
Introduction -- Definition of communities -- Evaluating communities --
Methodologies of Network Community Mining: Optimization based
algorithms -- Heuristic methods -- Other methods -- Applications of
community mining algorithms -- Multi-Relational characterization of
dynamic social network communities.

{{{unit}}}
|UNIT IV | PRACTICAL APPROACH TO SOCIAL NETWORK ANALYSIS | 9 |
Graph Theory: Introduction -- Adjacency matrices -- Graph Traversals and Distances -- Graph Distance; SNA Tool: Get oriented with
Python and NetworkX -- Centrality; Clique, Clusters and Components: Components and Subgraphs -- Triads -- Cliques -- Hierarchical
Clustering; 2-Mode networks; A dynamic model in Python. 


{{{unit}}}
|UNIT V | VISUALIZATION AND APPLICATIONS OF SOCIAL NETWORKS | 9 |
# Graph theory -- Centrality -- Clustering -- 
Visualizing online social networks -- Visualizing social networks with
matrix-based representations -- Node-Edge diagrams -- Matrix and
Node-Link Diagrams -- Hybrid representations; Applications: Covert
networks -- Community welfare -- Collaboration networks -- Co-citation
networks.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 

1. Describe social network concepts, measures and data (K2)
2. Apply social networks concepts using formal methods (K3)
3. Compare the working of community detection algorithms (K2)
4. Apply SNA concepts for social networks using NetworkX tool (K3)
5. Design and analyse social networks using visualization tools to solve real world problems (K4)



** TEXTBOOKS
1. Stanley Wasserman, Katherine Faust, ``Social Network Analysis
   Methods and Applications'', 1st Edition, Cambridge University
   Press, 1999. (Unit I and Unit II)
2. Borko Furht, ``Handbook of Social Network Technologies and
   Applications'', 1st Edition, Springer, 2010. (Unit III and Unit V)

      
** REFERENCES
1. Peter Mika, ``Social Networks and the Semantic Web'', 1st Edition,
   Springer, 2007 (Unit I).
2. Maksim Tsvetovat and Alexander Kouznetsov, ``Social Network
   Analysis for Startups'', O’Reilly, 2011 (Unit IV).
3. Edward L. Platt, ``Network Science with Python and NetworkX Quick
   Start Guide: Explore and visualize network data effectively'',
   Packt Publishing, 2019.
4. Stephen P Borgatti, Martin G Everett, Jeffrey G Johnson,
   ``Analyzing Social Networks'', SAGE Publications, 2nd
   Edition, 2018.
5. Charles Kadushin, ``Understanding Social Networks: Theories, Concepts, and Findings'', 1st Edition, Kindle Edition, Oxford
   University Press, 2012.

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 2 |  |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO2    | 3 | 2 |  |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO3    | 3 | 2 |  |  |  |  |  |  |  |   |   |   | 3 |  |  |
| CO4    | 3 | 2 |  |  |  |  |  |  |  |   |   |   | 2 |  |  |
| CO5    | 3 | 3 | 3 | 3 | 3 |  |  |  |   |   |   | 3 |  | 2 |   |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Score  | 15 | 11 | 3 | 3 | 3 |  |  |  | 3 | 3 |  |  | 12 |  | 2 |
| Course | 3 | 3 | 3 | 3 | 3 |  |  |  | 3 | 3 |    |   | 3 |  | 2 |
