* 
:properties:
:author: Dr. S. Saraswathi and Dr. K. Madheswari
:date: 29-03-2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE        | L | T | P | E | C |
| UCS2731 | AGILE METHODOLOGIES | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. We have verified the syllabus with industry expert.
2. No changes made in the syllabus
3. Books are updated to recent edition.
4. 1-6 : 1
5. 7-12: 2
6. 13-18: 3
7. Anna University Regulation 2017 has this course. 
8. The syllabus content across units were modified in Autonomous syllabus as adviced by the domain expert committee.
10. Five Course outcomes specified and aligned with units


** COURSE OBJECTIVES
- To understand the basic concepts of Agile software process
- To learn about agile requirement engineering
- To learn planning and management in agile software development
- To study various agile methods
- To learn the principles of agile testing and quality assurance. 

{{{unit}}}
| UNIT I | INTRODUCTION | 9 |
Iterative and Evolutionary Development; Introduction to Agile: Agile
development -- Classification of methods -- Agile manifesto and
principles -- Communication and feedback -- Specific agile methods --
Agile modelling; Theories for Agile Management; Management Accounting
for Systems; Agile Project Management: Traditional versus RAD model
for project management -- Task planning and effort tracking -- The
project manager's new work.
#+begin_comment
The topics Iterative and Evolutionary Development is added to differentiate agile from other methodologies.
References: Text book 2 (Chapter 2,3),  Text Book1  Chapters:1,2,6
#+end_comment

{{{unit}}}
| UNIT II | REQUIREMENTS ENGINEERING FOR AGILE METHODS | 9 |
Traditional and Agile Requirement Engineering; Methods and Tools for
Agile Practitioners: Requirements elicitation -- Requirements
representation and documentation -- Requirements analysis --
Requirements management; Agile Approaches to Requirements Engineering:
The customer -- Requirements evolution -- Non-functional requirements;
Tools for Requirements Management in AMs.
#+begin_comment
Focuses on agile requirement engineering whereas anna university syllabus on unit II is about agile process that not in flow 
Refernces: Reference book 4 and 5
#+end_comment

{{{unit}}}
| UNIT III | AGILE PROJECT PLANNING AND DEVELOPMENT MANAGEMENT | 9 |
Agile Project Planning: The Project buffer and its usage -- Logical
collection of inventory -- Critical path -- Parallel path -- Critical
chain -- Project tracking metrics; Agile Development Management:
Identifying and monitoring the flow -- Bottleneck; Agile Maturity
Model: A new maturity model.
#+begin_comment
This unit in on agile project planning and developement  whereas anna university syllabus discuss on knowledge management
References: Text book1 Chapters:7,9,11
#+end_comment

{{{unit}}}
| UNIT IV | AGILE METHODS | 9 |
Scrum: Method overview -- Life cycle -- Work products -- Values --
Roles and practices -- Process mixtures -- Adoption strategies;
Extreme Programming; Unified Process; EVO.
#+begin_comment
Agile Methods are discussed whereas anna university syllabus discuss on Requirement Engineering that is not in flow
Reference:  Text Book 2 Chapters: 7,8,9,10
#+end_comment

{{{unit}}}
| UNIT V | AGILE TESTING AND QUALITY ASSURANCE | 9 |
Agile testing: Nine principles and six concrete practices for testing
on agile teams; Agile Metrics: Feature driven development (FDD) --
Financial and production metrics in FDD -- Agile approach to quality
assurance -- Test driven development; SMM: A process improvement
framework for agile requirements engineering practices--case study.
#+begin_comment
references: text book 3,refernce book1,text book1,reference book 2
Testing is added in addition to quality in anna university syllabus
  
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
1. Explain evolutionary, iterative and adaptive development methods (K2)
2. Apply agile software process in requirement engineering (K3)
3. Outline agile methods for project planning and developement (K2)
4. Choose agile methods for software design (K3)
5. Apply agile based testing with quality assurance (K3).
   
 #+begin_comment
modified on 20-07-2021 :  
co6:  Build a software project to solve a real world problem in teams by applying best practices of Agile methods (K5).
modified on 20-07-2021 :
co6: Select and build a software project to solve a real world problem in teams by applying best practices of Agile methods (K5).
#+end_comment

** TEXT BOOKS
1. David J. Anderson and Eli Schragenheim, ``Agile Management for Software Engineering: Applying the Theory of Constraints for Business Results``, Prentice Hall, 2003.
2. Craig Larman, ``Agile and Iterative Development: A Manager’s Guide``, Addison-Wesley, 2004.
3. Elisabeth Hendrickson, ``Agile Testing``, Quality Tree Software Inc 2008.

	
** REFERENCES
1. Hazza, Dubinsky, ``Agile Software Engineering, Series:
   Undergraduate Topics in Computer Science'',
   Springer, 2009. (Unit 5)
2. Chetankumar Patel, Muthu Ramachandran, ``Story Card Maturity Model
   (SMM): A Process Improvement Framework for Agile Requirements
   Engineering Practices'', Journal of Software, Academy Publishers,
   Vol 4, No 5, 422-435, Jul 2009. (Unit 5)
3. Kevin C Desouza, ``Agile Information Systems: Conceptualization,
   Construction, and Management'', Butterworth-Heinemann, 2007.
4. Didar Zowghi, Zhi Jin, ``Requirements Engineering'', Springer ,
   chapter 15, 2014. (Unit 2)
5. Aybuke Aurum, Claes Wohlin, ``Engineering and Managing Software
   Requirements'', Springer 2005, chapter 14. (Unit 2)

** CO TO PO/PSO MAPPING
| PO/PSO |  1 |  2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |  1 | 2 | 3 |
|--------+----+----+---+---+---+---+---+---+---+----+----+----+----+---+---|
| CO1    |  3 |  2 |   |   |   |   |   |   |   |    |    |    |  2 |   |   |
| CO2    |  3 |  2 | 2 |   |   |   |   |   |   |    |    |    |  2 |   |   |
| CO3    |  3 |  2 | 2 |   |   |   |   |   |   |    |    |    |  2 |   |   |
| CO4    |  3 |  2 | 2 |   |   |   |   |   |   |    |    |    |  2 |   |   |
| CO5    |  3 |  3 | 3 |   |   |   |   |   |   |    |    |    |  2 | 3 |   |
|--------+----+----+---+---+---+---+---+---+---+----+----+----+----+---+---|
| Score  | 15 | 11 | 9 |   |   |   |   |   |   |    |    |    | 10 | 3 |   |
| Course |  3 |  3 | 3 |   |   |   |   |   |   |    |    |    |  2 | 3 |   |
