* 
:properties:
:author: Dr. A. Beulah and Dr. J. Bhuvana
:date: 29-03-2021
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                 | L | T | P | E | C |
| UCS2734 | MOBILE AND WIRELESS SECURITY | 3 | 0 | 0 | 0 | 3 |


** R2021 CHANGES :noexport:
- New course
- Yet to do co-po mapping, c-objs, c-outcomes, ref


** COURSE OBJECTIVES
- To Understand vulnerabilities of wired and wireless networks
- To acquire knowledege on  Bluetooth, Wi-Fi and Ad Hoc Networks Security 
- To Understand the secuirty in cellular networks 
- To learn about mobile hardware and software security


{{{unit}}}
| UNIT I | VULNERABILITIES OF WIRED AND WIRELESS NETWORKS | 9 |
Introduction: Security in the digital age -- Threats and risks to telecommunications systems -- From wireline vulnerabilities to vulnerabilities in wireless communications.
Fundamental Security Mechanisms : Basics on security --  Authentication --Access control.

{{{unit}}}
| UNIT II | WIRELESS SECURITY | 12 |
#+begin_comment
Bluetooth, Wi-Fi and Ad Hoc Networks Security 
#+end_comment
Bluetooth technical specification -- Bluetooth security.
Wi-Fi Security: Attacks on wireless networks -- Security in the IEEE 802.11-- Security in 802.1x -- Authentication in wireless networks -- Layer 3 security mechanisms.
Security in Ad Hoc Networks :  Attacks to routing protocols -- Security mechanisms.

{{{unit}}}
| UNIT III | SECURITY IN MOBILE TELECOMMUNICATION NETWORKS | 8 |
Security in the GSM: Security mechanisms in GSM -- Security flaws in
GSM radio access -- Security flaws in GSM signaling; GPRS security:
GPRS architecture -- GPRS security mechanisms -- 3G security: UMTS
infrastructure -- UMTS security ; 4G Security.

{{{unit}}}
| UNIT IV | MOBILE HARDWARE SECURITY | 8 |
Platform Boot Integrity -- Secure Storage -- Isolated Execution --
Device Identification -- Device Authentication -- Hardware Security
Architectures -- TEE Standards.

{{{unit}}}
| UNIT V | MOBILE PLATFORM SECURITY | 8 |
Android Based Security: Attacks and Threats -- Security extensions for
Android.  iOS Based security: Limits of Apple's application vetting
process -- iOS security extensions.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Outline the vulnerabilities of wired and wireless networks (K2)
2. Examine the security mechanism followed in Bluetooth, Wi-Fi and Ad Hoc Networks (K3)
3. Compare the security mechanisms of telecommunication networks   (K3)
4. Explain Hardware Security Architectures in mobile devices (K2)
5. Examine the Android and iOS Based Security (K3).

   
** TEXT BOOKS
1. Hakima Chaouchi, Maryline Laurent-Maknavicius, ``Wireless and
   Mobile Network Security- Security Basics, Security in On-the-shelf
   and Emerging Technologies'', Wiley-ISTE, June 2009 (Unit I--III).
2. N. Asokan, Lucas Vincenzo Davi, Alexandra Dmitrienko, Stephan
   Heuser, Kari Kostiainen, Elena Reshetova, Ahmad-Reza Sadeghi,
   ``Mobile Platform Security'', Synthesis Lectures on Information
   Security, Privacy, and Trust, Morgan &Claypool Publishers, 2013
   (Unit IV, V).

** REFERENCES
1. Xiao, Yang, Shen, Xuemin Sherman, Du, Ding-Zhu, `` Wireless Network
   Security'', Springer, 2007.
2. Noureddine Boudriga, ``Security of Mobile Communications'', CRC
   Press, 2019
3. Levente Buttyan, Jean-Pierre Hubaux, ``Security and Cooperation in
   Wireless Networks'', Cambridge University Press, 2012
4. James Kempf, ``Wireless Internet Security: Architectures and
   Protocols'', Cambridge University Press, 2010
5. Patrick Traynor, Patrick McDaniel, Thomas La Porta, ``Security for
   Telecommunications Networks'', Springer, 2008

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 | 3 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO2    | 3 | 3 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO3    | 1 | 3 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO4    | 2 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO5    | 2 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  1 | 2 | 0 | 0 |

# | Score | 11 | 11 | 2 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 9 | 0 | 0 |

