* 
:properties:
:author: Dr. K. R. Sarath Chandran and Ms. S. Angel Deborah
:date: 09/03/2021(Revison)/ 29/03/2021(Changes highlighted), 13.06.21 (co-po mapping updated), 17.07.21(PSO2 updated and Action verbs checked), last update:11/03/2022
:end:


#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE             | L | T | P | E | C |
| UCS2825 | INTRODUCTION TO ROBOTICS | 3 | 0 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. Same as R2018

** COURSE OBJECTIVES
- To understand the basic concepts associated with the design,
  functioning, applications and social aspects of robots
- To study about the electrical drive systems and sensors used in
  robotics for various applications
- To learn about analyzing robot kinematics, dynamics through
  different methodologies and study various design aspects of robot
  arm manipulator and end-effector
- To learn about various motion planning techniques and the associated
  control architecture
- To understand the implications of AI and other trending concepts of
  robotics.

{{{unit}}}
| UNIT I | FOUNDATION | 9 |
Introduction -- Brief history -- Definition -- Anatomy -- Types --
Classification -- Specification and need based applications -- Role and
need of robots for the immediate problems of the society -- Future of
mankind and automation-ethical issues -- Industrial scenario local and
global -- Case studies on mobile robot research platform and industrial
serial arm manipulator.

{{{unit}}}
| UNIT II | BUILDING BLOCKS OF A ROBOT | 9 |
Types of electric motors : DC -- Servo -- Stepper; Specification -- Drives
for motors -- Speed & direction control and circuitry -- Selection
criterion for actuators -- Direct drives -- Non-traditional actuators -
Sensors for localization -- Navigation -- Obstacle avoidance and path
planning in known and unknown environments -- Optical -- Inertial --
Thermal -- Chemical -- Biosensor -- Other common sensors -- Case study on
choice of sensors and actuators for maze solving robot and self
driving cars.

{{{unit}}}
| UNIT III | KINEMATICS, DYNAMICS AND DESIGN OF ROBOTS & END-EFFECTORS | 9 |
Robot kinematics -- Geometric approach for 2R, 3R manipulators -- 
homogenous transformation using D-H representation -- Kinematics of WMR --
Lagrangian formulation for 2R robot dynamics -- Mechanical design
aspects of a 2R manipulator, WMR -- End-effector : Common types and
design case study.

{{{unit}}}
| UNIT IV | NAVIGATION, PATH PLANNING AND CONTROL ARCHITECTURE | 9 |
Mapping & Navigation -- SLAM, Path planning for serial manipulators --
Types of control architectures -- Cartesian control -- Force control and
hybrid position/force control -- Behaviour based control -- Application of
Neural network, fuzzy logic, optimization algorithms for navigation
problems -- Programming methodologies of a robot.

{{{unit}}}
|UNIT V | AI AND OTHER RESEARCH TRENDS IN ROBOTICS | 9 |
Application of Machine learning -- AI -- Expert systems -- Tele-robotics
and Virtual reality -- Micro & Nanorobots -- Unmanned vehicles -- Cognitive
robotics -- Evolutionary robotics -- Humanoids.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to 
1. Summarize the concepts of industrial robots (K2)
2. Apply different sensors and actuators for applications like maze solving and self driving cars (K3)
3. Model a 2R robot & an end-effector and solve the kinematics and dynamics of motion for robots (K3)
4. Apply the navigation and path planning techniques for robot motion planning (K3)
5. Outline the impact and progress of AI in the field of robotics (K2).


** TEXT BOOKS
1. Roland Siegwart, Illah Reza Nourbakhsh, ``Introduction to
   Autonomous Mobile Robots'', MIT Press, 2011.
2. Saeed B Niku, ``Introduction to Robotics, Analysis, System,
   Applications'', Pearson educations, 2002.

** REFERENCES
1. Richard David Klafter, Thomas A Chmielewski, Michael Negin,
   ``Robotic engineering: An Integrated Approach'', Prentice
   Hall, 1989.
2. Craig, J J, ``Introduction to Robotics: Mechanics and Control'',
   2nd Edition, Addison-Wesley, 1989.
3. K S Fu, R C Gonzalez and C S G Lee, ``Robotics: Control,
   Sensing, Vision and Intelligence'', McGraw-Hill, 1987.
4. Wesley E Snyder R, ``Industrial Robots, Computer Interfacing and
   Control'', Prentice Hall International Edition, 1988.
5. Robin Murphy, ``Introduction to AI Robotics'', MIT Press, 2000.

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 3 |   |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO2    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO3    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 3 |   |   |
| CO4    | 3 | 2 |   |   |   |   |   |   |   | 3  |    | 3  | 3 |   |   |
| CO5    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 3 | 3 |   |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Score | 15 | 8 |   |   |   |   |   |   |   |  3 |    | 3  |13 | 3 |   |
| Course mapping | 3 | 2 |   |   |   |   |   |   |   | 3 |    | 3  | 2 | 3 |   |

