* 
:properties:
:author: Dr. K. Vallidevi and Ms. Y. V. Lokeswari
:date: 17/3/21 
:end:

#+startup: showall
{{{title-tab}}}
| CODE    | COURSE TITLE                  | L | T | P | E | C |
| UCS2823 | SERVICE ORIENTED ARCHITECTURE | 3 | 0 | 0 | 0 | 3 |

#+begin_comment
Unit 1, 2, and 3 are same as R2017 Anna University Syllabus.  Unit 4:
Have included the topic "XML Web services for .Net" which is availale
in the second text book of the syllabus Unit 5: Replaced the old
content from the second text book they are more relevant to the
subject

Second Text book of Anna University Syllabus is altered, which is
authored by, Sahankar Kambhampaly...
#+end_comment

** COURSE OBJECTIVES
- To learn the fundamentals of XML
- To understand Service Oriented Architecture, Web services and
  their importance
- To know the web services standards and technologies
- To study the web service extensions
- To develop SOA based applications using service oriented analysis
  and design.

{{{unit}}}
|UNIT I|XML TECHNOLOGIES |9| 
XML Document Structure: Well-formed and valid documents -- DTD -- XML
 schema; Parsing XML using DOM -- SAX; XPath -- XML transformation and
 XSLT -- Xquery.

{{{unit}}}
| UNIT II | SERVICE ORIENTED ARCHITECTURE  BASICS |9|
Characteristics of SOA -- Benefits of SOA -- Comparing SOA with client
 server and distributed architectures -- Principles of service
 orientation -- Service layers.

{{{unit}}}
| UNIT III | WEB SERVICES AND STANDARDS |8|
Web Services Platform -- Service descriptions -- WSDL -- Messaging with SOAP --
 Service discovery -- UDDI -- Service level interaction patterns -- Orchestration and choreography.

{{{unit}}}
| UNIT IV | WEB SERVICES EXTENSIONS |8|
WS-Addressing -- WS-Reliable messaging -- WS-Policy -- WS-Coordination -- WS-Transactions --
 WS-Security -- Examples -- XML web services for .Net.


{{{unit}}}
|UNIT V|SERVICE ORIENTED ANALYSIS AND DESIGN |11|
Service oriented enterprise applications -- Service Oriented Analysis and Design: Need for models -- 
Principles of service design -- Design of activity services -- Design of data services -- 
Design of client services -- Design of business process services.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to 
1. Illustrate XML technologies (K2)
2. Explain service orientation, benefits of SOA (K2)
3. Build web services and WS standards (K3)
4. Apply web services extensions to develop solutions (K3)
5. Apply service modeling, service oriented analysis and design for
   application development in teams (K3).

** TEXT BOOKS
1. Thomas Erl, ``Service Oriented Architecture: Concepts, Technology,
   and Design'', Pearson Education, 2005.
2. Sahankar Kambhampaly, ``Service-Oriented Architecture for
   Enterprise Applications'', Wiley India Pvt.Ltd, 2008

** REFERENCES
1. James McGovern, Sameer Tyagi, Michael E Stevens, Sunil Mathew,
   ``Java Web Services Architecture'', Elsevier, 2003.
2. Ron Schmelzer et al, ``XML and Web Services'', Pearson
   Education, 2002.
3. Frank P Coyle, ``XML, Web Services and the Data Revolution'',
   Pearson Education, 2002.
4. Sandeep Chatterjee, James Webber, ``Developing Enterprise Web
   Services: An Architect's Guide'', Prentice Hall, 2004.
5. Eric Newcomer, Greg Lomow, ``Understanding SOA with Web
   Services'', Pearson Education, 2005.

** CO TO PO/PSO MAPPING

| PO/PSO | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 1 | 2 | 3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 2 | 2 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 1 | 0 | 0 |
| CO2    | 2 | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0 |  0 |  0 |  0 | 1 | 0 | 0 |
| CO3    | 3 | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 2 |  1 |  2 |  1 | 2 | 2 | 0 |
| CO4    | 3 | 3 | 2 | 0 | 0 | 0 | 0 | 1 | 0 |  0 |  0 |  0 | 2 | 0 | 0 |
| CO5    | 3 | 2 | 2 | 2 | 1 | 0 | 0 | 1 | 3 |  2 |  2 |  1 | 2 | 0 | 1 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 3 | 2 | 1 | 1 | 0 | 0 | 1 | 1 |  1 |  1 |  1 | 2 | 1 | 1 |

# | Score | 13 | 11 | 9 | 2 | 1 | 0 | 0 | 2 | 5 | 3 | 4 | 2 | 8 | 2 | 1 |
